openwrt:
  url: ~
  username: ~
  password: ~
mqtt:
  host: ~
  port: 1883
  username: ~
  password: ~
  retain: true
  topics:
    discovery: homeassistant
    base: openwrt2mqtt
mac_resolver:
  url: https://www.macvendorlookup.com/
debug: false
